import { relations } from "drizzle-orm";
import { boolean, integer, pgTable, text, timestamp, varchar, primaryKey } from "drizzle-orm/pg-core";

/**
 * This is the stuff that was generated by Better Auth
 */

export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified')
    .$defaultFn(() => false)
    .notNull(),
  image: text('image'),
  createdAt: timestamp('created_at')
    .$defaultFn(() => /* @__PURE__ */ new Date())
    .notNull(),
  updatedAt: timestamp('updated_at')
    .$defaultFn(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const session = pgTable('session', {
  id: text('id').primaryKey(),
  expiresAt: timestamp('expires_at').notNull(),
  token: text('token').notNull().unique(),
  createdAt: timestamp('created_at').notNull(),
  updatedAt: timestamp('updated_at').notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
});

export const account = pgTable('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at'),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
  scope: text('scope'),
  password: text('password'),
  createdAt: timestamp('created_at').notNull(),
  updatedAt: timestamp('updated_at').notNull(),
});

export const verification = pgTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at').$defaultFn(
    () => /* @__PURE__ */ new Date()
  ),
  updatedAt: timestamp('updated_at').$defaultFn(
    () => /* @__PURE__ */ new Date()
  ),
});

/**
 * END OF BETTER AUTH STUFF
 */

export const books = pgTable("books", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  title: varchar({ length: 255 }).notNull(),
  authors: varchar({ length: 255 }),
  isbn13: varchar().notNull().unique(),
  coverImage: text(),
  publishedYear: integer(),
  description: text()
});

export const userToBooks = pgTable(
  'user_to_books',
  {
    userId: text("user_id").notNull().references(() => user.id),
    bookId: integer("book_id").notNull().references(() => books.id),
    addedAt: timestamp("added_at").defaultNow().notNull()
  },
  (t) => [primaryKey({ columns: [t.userId, t.bookId] })]
)

export const bookclubs = pgTable("bookclubs", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  name: varchar({ length: 255 }).notNull(),
  description: text().notNull()
});

export const usersToBookclubs = pgTable('users_to_bookclubs', {
  userId: text('user_id').notNull().references(() => user.id),
  bookclubId: integer('bookclub_id').notNull().references(() => bookclubs.id),
  isOwner: boolean('is_owner').default(false).notNull()
}, (t) => [ primaryKey({ columns: [t.userId, t.bookclubId ]})])

export const userRelations = relations(user, ({ many }) => ({
  usersToBookclubs: many(usersToBookclubs)
}))

export const bookclubRelations = relations(bookclubs, ({ many }) => ({
  usersToBookclubs: many(usersToBookclubs)
}))

export const usersToBookclubsRelations = relations(usersToBookclubs, ({ one }) => ({
  bookclub: one(bookclubs, {
    fields: [usersToBookclubs.bookclubId],
    references: [bookclubs.id]
  }),
  user: one(user, {
    fields: [usersToBookclubs.userId],
    references: [user.id]
  })
}))