import { relations } from "drizzle-orm";
import { boolean, integer, pgTable, text, timestamp, varchar, primaryKey } from "drizzle-orm/pg-core";

/**
 * This is the stuff that was generated by Better Auth
 */

export const user = pgTable("user", {
  id: integer("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const session = pgTable("session", {
  id: integer("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: integer("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

export const account = pgTable("account", {
  id: integer("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: integer("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const verification = pgTable("verification", {
  id: integer("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

/**
 * END OF BETTER AUTH STUFF
 */

export const books = pgTable("books", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  name: varchar({ length: 255 }).notNull(),
  isbn13: integer().notNull(),
});

export const bookclubs = pgTable("bookclubs", {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  name: varchar({ length: 255 }).notNull(),
  description: text().notNull()
});

export const usersToBookclubs = pgTable('users_to_bookclubs', {
  userId: integer('user_id').notNull().references(() => user.id),
  bookclubId: integer('bookclub_id').notNull().references(() => bookclubs.id),
  isOwner: boolean('is_owner').default(false).notNull()
}, (t) => [ primaryKey({ columns: [t.userId, t.bookclubId ]})])

export const userRelations = relations(user, ({ many }) => ({
  usersToBookclubs: many(usersToBookclubs)
}))

export const bookclubRelations = relations(bookclubs, ({ many }) => ({
  usersToBookclubs: many(usersToBookclubs)
}))

export const usersToBookclubsRelations = relations(usersToBookclubs, ({ one }) => ({
  bookclub: one(bookclubs, {
    fields: [usersToBookclubs.bookclubId],
    references: [bookclubs.id]
  }),
  user: one(user, {
    fields: [usersToBookclubs.userId],
    references: [user.id]
  })
}))